---
title: "Day 2 Tasks"
author: "Erica Bishop"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Part 1. Checking data types

Hint from Allison: to look at one piece of data frame (df), use df %>% filter(column == "value")

```{r}
vec_1 <- c(2, 5, 9, 10, 8, 12, 1, 0)
class(vec_1)
typeof(vec_1)

#numeric calss, doubles type

#access third element and store:

vec_1_e3 <- vec_1[3]

vec_1_e1 <- vec_1[1]

vec_1_e5to7 <- vec_1[5:7]

#now reassign vec_1 as character

vec_1_char <- as.character(vec_1)

vec_1_char

```

Now create a second vector

```{r}

vec_2 <- c(town = "Santa Barbara",
           location = "Rincon",
           swell = "south")

#check it out

vec_2

class(vec_2)

length(vec_2)

vec_2_e2 <- vec_2["location"]

```

Now create a data frame

```{r}

df_1 <- data.frame(region = c("A", "B", "A", "D"),
                   species = c("otter", "great white", "sea lion", "gray whale"),
                   count = c(12, 2, 36, 6))

df_1

class(df_1)
class(df_1$species)

max_count <- max(df_1$count)
max_count

```







